name: Build and Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '**'

jobs:
  gradle:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Check if google-java-format changed anything
        run: git --no-pager diff --exit-code

      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test